# -------------------------------
# user-defined configuration file
# -------------------------------
user_id: "bldelane" # CERN user ID for kinit @CERN.CH

# test-run configuration
# =======================
max_events: -1 # -1 for all events


# data-taking configuration
# ==========================
years:
  - "2011"
  - "2012"
  - "2015"
  - "2016"
  - "2017"
  - "2018"
magpols:
  - "MU"
  - "MD"
data_types:
  - "data"
  - "mc"


# remote ntuple configuration
# ===========================
channel:
  butojpsik_mm: # B+ -> J/psi(->mumu) K+s
    key: "bu2kmumutuple"
    tree: "DecayTree"
    boi: # Branches Of Interest
      - "Kplus_PIDmu"
      - "Kplus_PIDe"
      - "Kplus_PIDp"
      - "Kplus_PIDK"
      - "Kplus_isMuon"
      - "Kplus_hasMuon"
      - "Kplus_hasRich"
      - "Kplus_LOKI_PP_InAccMuon"
      - "Kplus_ProbNNghost"
      # - "Bplus_DTF_MASS_JPsi_Constr_J_psi_1S_M"
      # - "Bplus_DTF_MASS_JPsi_Constr_M"
      # - "Bplus_LOKI_DTF_MASS_Bu_Constr"
      - "Bplus_M"
      - "J_psi_1S_M"
      - "Kplus_LOKI_ETA"
      - "nTracks"
      - "Bplus_L0Global_TIS"
      - "muplus_L0MuonDecision_TOS"
      - "muminus_L0MuonDecision_TOS"
      - "Kplus_PT"
      - "Kplus_P"
      - "Kplus_TRUEID"
      - "Bplus_TRUEID"
      - "Bplus_BKGCAT"
    selection:
      common_criteria: "( (Bplus_Hlt1TwoTrackMVADecision_TOS==1.0) | (Bplus_Hlt1TrackMVADecision_TOS==1.0) ) &\
          ( (Bplus_Hlt2Topo2BodyDecision_TOS==1.0) | (Bplus_Hlt2Topo3BodyDecision_TOS==1.0) ) & \
          ( (Kplus_PT>250) & (Kplus_P>10e3) & (Kplus_P<100e3) & (J_psi_1S_M>3096-50) & (J_psi_1S_M<3096+50) )"
      stripping_pid: "( (Kplus_hasRich==1.0) & (Kplus_PIDK>-5.0) )" # https://gitlab.cern.ch/lhcb/Stripping/-/blob/2018-patches/Phys/CommonParticlesArchive/python/CommonParticlesArchive/Stripping34/CommonParticles/StdAllLooseKaons.py?ref_type=heads
      lzero: "( (Bplus_L0Global_TIS==1.0) | (muplus_L0MuonDecision_TOS==1.0) | (muminus_L0MuonDecision_TOS==1.0) )"
      truth_matching: "( (Kplus_TRUEID==0) & (Bplus_TRUEID==0) & (Bplus_BKGCAT==60) )" # applied to study ghost PID response in DDmisID


# storage configuration for output files
# ======================================
output_storage  : "/ceph/submit/data/user/b/blaised/trex"