# -------------------------------
# user-defined configuration file
# -------------------------------

# authentication credentials - kinit @CERN.CH for EOS storage access
# ==================================================================
user_id: "bldelane" 


# test-run configuration
# =======================
max_events: -1 # -1 for all events


# data-taking configuration
# ==========================
years:
  - "2011"
  - "2012"
  - "2015"
  - "2016"
  - "2017"
  - "2018"
magpols:
  - "MU"
  - "MD"
data_types:
  - "data"
  - "mc"


# remote ntuple configuration
# ===========================
channel:
  butojpsik_mm: # B+ -> J/psi(->mumu) K+s
    key: "B2Kmumu_Tuple"
    tree: "DecayTree"
    boi: # Branches Of Interest
      - "B_plus_L0Global_TIS"
      - "e_plus_L0MuonDecision_TOS" # naming convention in RX framework
      - "e_minus_L0MuonDecision_TOS" # naming convention in RX framework
      - "K_Kst_PT"
      #- "B_plus_DTFM_J_psi_1S_M"
      - "B_plus_M"
      - "K_Kst_ETA" # naming convention in RX framework
    # aliases: # NOTE: store as a single dict
    #   "B_plus_DTF_M" : "B_plus_DTFM_J_psi_1S_M"
    selection:
      mass: "( (B_plus_M>5_200) & (B_plus_M<5_400) )"
      pid: "(K_Kst_PIDK>0.0)" 
      lzero: "( (e_plus_L0MuonDecision_TOS==1.0) | (e_minus_L0MuonDecision_TOS==1.0) )"
      truth_matching: "( (abs(B_plus_TRUEID)==521) & (J_psi_1S_TRUEID==443) & (abs(J_psi_1S_MC_MOTHER_ID)==521) & (abs(e_plus_TRUEID)==13) & (e_plus_MC_MOTHER_ID==443) & (abs(e_minus_TRUEID)==13) & (e_minus_MC_MOTHER_ID==443) & (abs(K_Kst_TRUEID)==321) & (abs(K_Kst_MC_MOTHER_ID)==521) & (B_plus_BKGCAT==0) )"
        # signal: "( (abs(Bplus_TRUEID)==521) & (J_psi_1S_TRUEID==443) & (abs(J_psi_1S_MC_MOTHER_ID)==521) & (abs(muplus_TRUEID)==13) & (muplus_MC_MOTHER_ID==443) & (abs(muminus_TRUEID)==13) & (muminus_MC_MOTHER_ID==443) & (abs(Kplus_TRUEID)==321) & (abs(Kplus_MC_MOTHER_ID)==521) & (Bplus_BKGCAT==0) )"
        # misid: "(Bplus_BKGCAT==30)"


# binning scheme for the TISTOS study 
# ===================================
binning_scheme: # NOTE: store as a single dict
    "K_Kst_PT" : [0, 1_500, 3_000, 5_0000, 10_000, 15_000, 25_000, 100_000]
    "K_Kst_ETA" : [1.5, 2.5, 3.5, 5.5]


# storage configuration for output files
# ======================================
output_storage  : "/ceph/submit/data/user/b/blaised/trex/bu2kmumu/"